Repository spinnaker/orca, pull requests merged in 2019-10, with the labels that each got.

#2820 fix(pipelines): Fixed interpretation of missing startTime during inst…
  orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
  orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
  orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt
Labels: ready

#3235 chore(github): Add mergify config
  .mergify.yml
Labels: ready to merge

#3236 fix(bake): Fix the fix for inconsistent names in parallel bakes
  orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy
  orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStageSpec.groovy
Labels: ready to merge

#3239 fix(rrb): Store RRB before-cleanup pipeline ID in the right context field
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategySpec.groovy
Labels: ready to merge

#3242 feat(plugins): Add kork-plugins, wire up initial spel function extension point
  gradle.properties
  orca-core/orca-core.gradle
  orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
  orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java
  orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java
  orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluatorSpec.groovy
Labels: ready to merge

#3249 fix(conditions): invalid stageEnabled expressions disable stage
  orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/OptionalStageSupport.java
Labels: ready to merge

#3248 feat(plugins): Back orca stage plugins via PF4J
  orca-api/orca-api.gradle
  orca-api/src/main/java/com/netflix/spinnaker/orca/api/SimpleStage.java
  orca-core/src/main/java/com/netflix/spinnaker/orca/StageResolver.java
  orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
Labels: ready to merge

#3255 fix(monitored deploy): add deploymentId parameter
  orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/orca/deploymentmonitor/models/RequestBase.java
Labels: auto merged, ready to merge

#3258 fix(dependent pipelines): failure to trigger a dependend pipeline shouldn't affect others
  orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy
  orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListenerSpec.groovy
Labels: auto merged, ready to merge

#3259 fix(kayenta): Make sure we destroy canary clusters
  orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/pipeline/CleanupCanaryClustersStage.kt
  orca-kotlin/src/main/kotlin/com/netflix/spinnaker/orca/ext/Stage.kt
Labels: auto merged, ready to merge

#3234 feat(cfn): request to delete CFN changeset if empty
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/DeployCloudFormationStage.java
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeleteCloudFormationChangeSetTask.java
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/WaitForCloudFormationCompletionTask.java
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/DeployCloudFormationStageTest.groovy
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeleteCloudFormationChangeSetTaskSpec.groovy
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/WaitForCloudFormationCompletionTaskSpec.groovy
Labels: ready to merge

#3214 feat(monitoredDeploy): Completed event should include details of success/failure
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ClusterSizePreconditionTask.groovy
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/EvaluateDeploymentHealthTask.java
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/MonitoredDeployBaseTask.java
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/NotifyDeployCompletedTask.java
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/NotifyDeployStartingTask.java
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/NotifyDeployCompletedTaskSpec.groovy
  orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java
  orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/orca/deploymentmonitor/models/DeploymentCompletedRequest.java
  orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/orca/deploymentmonitor/models/MonitoredDeployInternalStageData.java
Labels: ready to merge

#3260 feat(kustomize): add kustomizeFilePath to support gitrepo artifact type
  orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/manifests/kustomize/KustomizeBakeManifestRequest.java
  orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/BakeManifestContext.java
Labels: ready to merge

#3265 fix(kubernetes): Fix Optional ofNullable
  orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/BakeManifestContext.java
Labels: ready to merge

#3264 feat(kubernetes): permit multiple ReplicaSets to be deployed with a s…
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
Labels: ready to merge

#3268 chore(api): Switch to kork-annotations from guava
  orca-api/src/main/java/com/netflix/spinnaker/orca/api/SimpleStage.java
  orca-api/src/main/java/com/netflix/spinnaker/orca/api/SimpleStageInput.java
  orca-api/src/main/java/com/netflix/spinnaker/orca/api/SimpleStageOutput.java
  orca-api/src/main/java/com/netflix/spinnaker/orca/api/SimpleStageStatus.java
Labels: auto merged, ready to merge

#3270 fix(cloudformation): Support Cloudformation templates as lists
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeployCloudFormationTask.java
Labels: auto merged, ready to merge
