Repository spinnaker/orca, pull requests merged in 2020-10, with the labels that each got.

#3938 fix(plugins): Rebuild task cache on call to get task by type identifier
  orca-core/src/main/java/com/netflix/spinnaker/orca/TaskResolver.java
  orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
Labels: ready to merge

#3941 Revert "fix(tasks): Only lookup task by type in RunTaskHandler; remove code introduced to support one-off case for now obsolete SimpleTask"
  orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/graph/TaskNode.java
  orca-core/src/main/java/com/netflix/spinnaker/orca/TaskResolver.java
  orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/StageDefinitionBuilders.kt
  orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
  orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
Labels: ready to merge

#3954 feat(gce): remove the deprecated ONLY_UP autoscaling mode
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/gce/WaitForGceAutoscalingPolicyTask.java
Labels: auto merged, ready to merge

#3958 chore(kork): update kork dependency (now w/ moniker)
  gradle.properties
  orca-clouddriver/orca-clouddriver.gradle
  orca-flex/orca-flex.gradle
  orca-kayenta/orca-kayenta.gradle
Labels: ready to merge

#3959 feat(clouddriver): Look ahead region detection for "aws" can be disabled
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy
Labels: ready to merge

#3934 feat(orca) Add support for Redis SSL
  keiko-redis-spring/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueConfiguration.kt
Labels: auto merged, ready to merge

#3946 feat(queue): Add command to cleanup zombie executions
  orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/ZombieExecutionService.kt
  orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/admin/web/QueueAdminController.kt
  orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/ZombieExecutionCheckingAgent.kt
  orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/ZombieExecutionServiceTest.kt
  orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/metrics/ZombieExecutionCheckingAgentTest.kt
Labels: auto merged, ready to merge

#3963 fix(preconfigured job): Fix for https://github.com/spinnaker/spinnaker/issues/6052
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStage.groovy
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStageSpec.groovy
Labels: ready to merge

#3964 fix(clouddriver): Re-enable the unit test `@Unroll`
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy
Labels: ready to merge

#3966 chore(kotlin): move to new kotlin version and upgrade kork
  build.gradle
  gradle.properties
  gradle/kotlin.gradle
Labels: ready to merge

#3965 fix(webhook): Pass stage configuration data to rest template provider…
  orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/service/DefaultRestTemplateProvider.java
  orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/service/RestTemplateProvider.java
  orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookService.groovy
  orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
  orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy
  orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookServiceSpec.groovy
  orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy
  orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTaskSpec.groovy
Labels: auto merged, ready to merge

#3943 feat(disable): add an optional waitForDisabledServerGroup task
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/ForceCacheRefreshAware.java
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ModifyAwsScalingProcessStage.groovy
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DisableServerGroupStage.groovy
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForDestroyedServerGroupTask.groovy
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForDisabledServerGroupTask.java
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ModifyAwsScalingProcessStageSpec.groovy
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategySpec.groovy
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/WaitForDestroyedAsgTaskSpec.groovy
  orca-core/orca-core.gradle
  orca-core/src/main/java/com/netflix/spinnaker/orca/clouddriver/utils/CloudProviderAware.java
  orca-core/src/main/java/com/netflix/spinnaker/orca/clouddriver/utils/Descriptors.kt
Labels: WIP - do not merge

#3969 fix(moniker): build instead of cast moniker from context
  orca-core/src/main/java/com/netflix/spinnaker/orca/clouddriver/utils/CloudProviderAware.java
Labels: ready to merge

#3970 feat(disable): put the disabled flag enforcement behind a feature toggle
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTaskSpec.groovy
Labels: ready to merge

#3975 fix(kayenta): Fixing nullable duration
  orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/KayentaService.kt
  orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/pipeline/RunCanaryIntervalsStage.kt
  orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/MonitorKayentaCanaryTask.kt
Labels: ready to merge

#3973 feat(SpelHelpers): Support parsing multi-document yaml strings
  orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/UrlExpressionFunctionProvider.java
  orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/UrlExpressionFunctionProviderSpec.groovy
Labels: ready to merge

#3976 fix(webhook): Capture response headers in the stage output
  orca-clouddriver/src/test/kotlin/com/netflix/spinnaker/orca/clouddriver/pipeline/KubernetesPreconfiguredJobSpec.kt
  orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy
  orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/WebhookResponseProcessor.java
  orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy
  orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTaskSpec.groovy
Labels: ready to merge

#3980 feat(clouddriver): Emit staleness metric around ephemeral server groups
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/EphemeralServerGroupsPoller.java
Labels: ready to merge

#3977 chore(queue): Clarify cancelation reason when purging waiting pipelines
  orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartWaitingExecutionsHandler.kt
  orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/messages.kt
Labels: auto merged, ready to merge

#3923 fix(wait): Fix wait for up instances task
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy
  orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTaskSpec.groovy
Labels: auto merged, ready to merge

#3978 fix(keel): read configuration for keel from services
  orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/config/KeelConfiguration.kt
Labels: auto merged, ready to merge
