Repository spinnaker/orca, pull requests merged in 2021-01, with the labels that each got.

#3998 feat(core): Add SpEL helper to get all resolved stage artifacts
  orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/ArtifactExpressionFunctionProvider.java
  orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/ArtifactExpressionFunctionProviderSpec.groovy
Labels: auto merged, ready to merge

#4037 Fix(manifest): Fix manifests resolved by Spel
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTask.java
  orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTaskTest.java
Labels: ready to merge

#4044 fix(manifest): Fix deployment of artifact only stages
  orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTask.java
  orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTaskTest.java
Labels: backport-candidate

#4056 fix(jenkins): Minor tweak to backlink config value per PR feedback
  orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorQueuedJenkinsJobTask.groovy
Labels: ready to merge
